const ISO: Record<string, string> = {
  Albania: "AL",
  Algeria: "DZ",
  Angola: "AO",
  Argentina: "AR",
  Australia: "AU",
  Azerbaijan: "AZ",
  Bahamas: "BS",
  Bahrain: "BH",
  Bangladesh: "BD",
  Belgium: "BE",
  Benin: "BJ",
  Brazil: "BR",
  Brunei: "BN",
  Bulgaria: "BG",
  Cambodia: "KH",
  Cameroon: "CM",
  Canada: "CA",
  Chile: "CL",
  China: "CN",
  Colombia: "CO",
  Comoros: "KM",
  "Costa Rica": "CR",
  "Côte d'Ivoire": "CI",
  Croatia: "HR",
  Cuba: "CU",
  Cyprus: "CY",
  Denmark: "DK",
  Djibouti: "DJ",
  "Dominican Republic": "DO",
  Ecuador: "EC",
  Egypt: "EG",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  Estonia: "EE",
  Finland: "FI",
  France: "FR",
  Gabon: "GA",
  Gambia: "GM",
  Georgia: "GE",
  Germany: "DE",
  Ghana: "GH",
  Greece: "GR",
  Guatemala: "GT",
  Guinea: "GN",
  "Guinea-Bissau": "GW",
  Guyana: "GY",
  Honduras: "HN",
  "Hong Kong": "HK",
  Iceland: "IS",
  India: "IN",
  Indonesia: "ID",
  Iran: "IR",
  Iraq: "IQ",
  Ireland: "IE",
  Israel: "IL",
  Italy: "IT",
  Jamaica: "JM",
  Japan: "JP",
  Jordan: "JO",
  Kenya: "KE",
  Kuwait: "KW",
  Latvia: "LV",
  Lebanon: "LB",
  Liberia: "LR",
  Libya: "LY",
  Lithuania: "LT",
  Madagascar: "MG",
  Malaysia: "MY",
  Malta: "MT",
  Mauritius: "MU",
  Mayotte: "YT",
  Mexico: "MX",
  Morocco: "MA",
  Mozambique: "MZ",
  Myanmar: "MM",
  Namibia: "NA",
  Netherlands: "NL",
  "New Zealand": "NZ",
  Nigeria: "NG",
  Norway: "NO",
  Oman: "OM",
  Pakistan: "PK",
  Panama: "PA",
  "Papua New Guinea": "PG",
  Peru: "PE",
  Philippines: "PH",
  Poland: "PL",
  Portugal: "PT",
  "Puerto Rico": "PR",
  Qatar: "QA",
  "Republic of Congo": "CG",
  Romania: "RO",
  Russia: "RU",
  "Saudi Arabia": "SA",
  Senegal: "SN",
  Seychelles: "SC",
  "Sierra Leone": "SL",
  Singapore: "SG",
  Somalia: "SO",
  "South Africa": "ZA",
  "South Korea": "KR",
  Spain: "ES",
  "Sri Lanka": "LK",
  Suriname: "SR",
  Sweden: "SE",
  Syria: "SY",
  Taiwan: "TW",
  Tanzania: "TZ",
  Thailand: "TH",
  Togo: "TG",
  "Trinidad & Tobago": "TT",
  Tunisia: "TN",
  Turkey: "TR",
  UAE: "AE",
  UK: "GB",
  USA: "US",
  Ukraine: "UA",
  Uruguay: "UY",
  Vietnam: "VN",
};

export const COUNTRIES = Object.keys(ISO).sort((a, b) => a.localeCompare(b));

export function countryCode(country: string): string {
  return ISO[country] ?? "";
}
