FROM node:20-slim

WORKDIR /app

# Install dependencies first for better layer caching
COPY package.json package-lock.json ./
RUN npm ci

# Copy the full project (including .env generated by the portal)
COPY . .

# Build client bundle + server boot bundle into dist/
RUN npm run build

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "dist/boot.js"]
