export const MEMBERSHIP_PLANS = [
  {
    tier: "SPROUT" as const,
    name: "Sprout",
    monthly: 2000,
    annual: 21600,
    tonnage: "Up to 50 tons / month",
    tonnageLimit: 50,
    features: [
      "Cost-to-cost pricing (no margin)",
      "Basic market insights dashboard",
      "30-day price trends",
      "Standard support",
    ],
    missing: ["Invoice financing", "Real-time AI recommendations", "Dedicated account manager"],
  },
  {
    tier: "HARVEST" as const,
    name: "Harvest",
    monthly: 5000,
    annual: 54000,
    tonnage: "51–200 tons / month",
    tonnageLimit: 200,
    features: [
      "Everything in Sprout",
      "Real-time insights dashboard",
      "Invoice financing up to £50k",
      "AI trade recommendations",
      "Priority support",
    ],
    missing: ["Dedicated account manager", "Custom analytics"],
  },
  {
    tier: "SCALE" as const,
    name: "Scale",
    monthly: 7000,
    annual: 75600,
    tonnage: "201+ tons / month",
    tonnageLimit: 1000,
    features: [
      "Everything in Harvest",
      "Dedicated account manager",
      "Financing up to £200k",
      "Custom analytics & reports",
      "Quarterly strategy reviews",
    ],
    missing: [] as string[],
  },
];
