import { z } from "zod";
import { desc, eq } from "drizzle-orm";
import { createRouter, authedQuery } from "./middleware";
import { getDb } from "./queries/connection";
import * as s from "@db/schema";
import { effUser, assertStaff, assertFinance, assertBuyer, genNumber, logActivity, notify, fmtActor } from "./rbac";

export const ordersRouter = createRouter({
  /** Staff: full order lifecycle view */
  list: authedQuery.query(async ({ ctx }) => {
    assertStaff(await effUser(ctx.user));
    return getDb().query.orders.findMany({
      with: {
        quote: { with: { request: { with: { buyer: { with: { organization: true } } } } } },
        shipment: true,
      },
      orderBy: desc(s.orders.createdAt),
      limit: 200,
    });
  }),

  /** Buyer: my orders */
  mine: authedQuery.query(async ({ ctx }) => {
    const me = await effUser(ctx.user);
    assertBuyer(me);
    const all = await getDb().query.orders.findMany({
      with: {
        quote: { with: { request: true } },
        shipment: true,
        invoices: true,
      },
      orderBy: desc(s.orders.createdAt),
      limit: 200,
    });
    return all.filter((o) => o.quote?.request?.buyerId === me.id);
  }),

  detail: authedQuery
    .input(z.object({ id: z.number() }))
    .query(async ({ ctx, input }) => {
      const me = await effUser(ctx.user);
      const order = await getDb().query.orders.findFirst({
        where: eq(s.orders.id, input.id),
        with: {
          quote: { with: { request: { with: { buyer: { with: { organization: true } } } }, supplier: { with: { organization: true } } } },
          shipment: true,
          invoices: true,
          documents: true,
        },
      });
      if (!order) throw new Error("Order not found");
      const isStaff = ["ADMIN", "OPERATIONS", "FINANCE", "SUPPORT"].includes(me.portalRole ?? "");
      if (!isStaff && order.quote?.request?.buyerId !== me.id && order.quote?.supplierId !== me.id) {
        throw new Error("Forbidden");
      }
      return order;
    }),

  generateInvoice: authedQuery
    .input(
      z.object({
        orderId: z.number(),
        type: z.enum(["PROFORMA", "COMMERCIAL", "PURCHASE_ORDER"]).default("PROFORMA"),
        installment: z.enum(["FULL", "DEPOSIT", "BALANCE"]).default("FULL"),
      }),
    )
    .mutation(async ({ ctx, input }) => {
      const me = await effUser(ctx.user);
      assertFinance(me);
      const db = getDb();
      const order = await db.query.orders.findFirst({
        where: eq(s.orders.id, input.orderId),
        with: { invoices: true },
      });
      if (!order) throw new Error("Order not found");
      // One invoice per installment per order
      if (order.invoices.some((inv) => inv.installment === input.installment)) {
        throw new Error(`A ${input.installment.toLowerCase()} invoice already exists for this order`);
      }
      // Paid-member schedule: 70% deposit, balance is the exact remainder so the two always sum to the total
      const deposit = Math.round(order.total * 0.7 * 100) / 100;
      const amount =
        input.installment === "DEPOSIT" ? deposit : input.installment === "BALANCE" ? Math.round((order.total - deposit) * 100) / 100 : order.total;
      const invoiceNumber = genNumber("INV");
      const [{ id }] = await db
        .insert(s.invoices)
        .values({
          orderId: input.orderId,
          invoiceNumber,
          type: input.type,
          installment: input.installment,
          amount,
          currency: "GBP",
          dueDate: new Date(Date.now() + 7 * 864e5),
        })
        .returning({ id: s.invoices.id });
      const label = input.installment === "FULL" ? input.type.toLowerCase() : `${input.installment.toLowerCase()} (${input.installment === "DEPOSIT" ? "70%" : "30%"})`;
      await logActivity(fmtActor(me), `Generated ${label} invoice ${invoiceNumber}`, "invoice", invoiceNumber, me.id);
      return { id, invoiceNumber, amount };
    }),

  /** Staff (Gate 2): issue the sales contract into the buyer's account.
   *  Aquifert-letterhead document, generated by staff action, which is itself
   *  the human clearance: it contains no counterparty identity. */
  issueContract: authedQuery
    .input(z.object({ orderId: z.number() }))
    .mutation(async ({ ctx, input }) => {
      const me = await effUser(ctx.user);
      assertStaff(me);
      const db = getDb();
      const order = await db.query.orders.findFirst({
        where: eq(s.orders.id, input.orderId),
        with: {
          quote: { with: { request: { with: { buyer: { with: { organization: true } } } } } },
          documents: true,
        },
      });
      if (!order) throw new Error("Order not found");
      if (order.documents.some((d) => d.type === "CONTRACT")) throw new Error("A contract already exists for this order");
      const req = order.quote?.request;
      const buyerName = req?.buyer?.organization?.name ?? req?.buyer?.name ?? "the buyer";
      const cleanText = [
        `Sales Contract ${order.orderNumber}`,
        ``,
        `This contract is made between Aquifert Ltd (the "Seller") and ${buyerName} (the "Buyer").`,
        ``,
        `Product: ${req?.product ?? "N/A"}`,
        `Quantity: ${req?.quantity ?? "N/A"} tons`,
        `Destination: ${req?.destination ?? "N/A"}`,
        `Incoterms: ${req?.incoterms ?? "N/A"}`,
        `Contract value: GBP ${order.total.toLocaleString()}`,
        `Payment schedule: 70% deposit on contract issue, 30% balance on release of shipping documents.`,
        ``,
        `Aquifert Ltd acts as principal. Counterparty identities remain confidential under the Aquifert trust model.`,
      ].join("\n");
      const [{ id }] = await db
        .insert(s.documents)
        .values({
          orderId: input.orderId,
          type: "CONTRACT",
          name: `Sales-Contract-${order.orderNumber}`,
          url: "#",
          uploadedBy: me.id,
          docClass: "A",
          gateState: "PASS",
          cleanText,
          clearedBy: me.id,
          clearedAt: new Date(),
          buyerReleasable: true,
        })
        .returning({ id: s.documents.id });
      if (req?.buyerId) {
        await notify(req.buyerId, "CONTRACT_ISSUED", "Contract issued", `Your sales contract for ${order.orderNumber} is now in your account.`, "/buyer/orders");
      }
      await logActivity(fmtActor(me), `Issued sales contract for ${order.orderNumber} (Gate 2 approval)`, "document", String(id), me.id);
      return { id };
    }),

  markPaid: authedQuery
    .input(z.object({ orderId: z.number(), invoiceId: z.number().optional() }))
    .mutation(async ({ ctx, input }) => {
      const me = await effUser(ctx.user);
      assertFinance(me);
      const db = getDb();
      const order = await db.query.orders.findFirst({
        where: eq(s.orders.id, input.orderId),
        with: { quote: { with: { request: true } }, invoices: true },
      });
      if (!order) throw new Error("Order not found");
      if (input.invoiceId) {
        const inv = order.invoices.find((i) => i.id === input.invoiceId);
        if (!inv) throw new Error("Invoice not found on this order");
        await db.update(s.invoices).set({ paidAt: new Date() }).where(eq(s.invoices.id, input.invoiceId));
      } else {
        await db.update(s.invoices).set({ paidAt: new Date() }).where(eq(s.invoices.orderId, input.orderId));
      }
      const fresh = await db.query.invoices.findMany({ where: eq(s.invoices.orderId, input.orderId) });
      const paidCount = fresh.filter((i) => i.paidAt).length;
      const allPaid = fresh.length > 0 && paidCount === fresh.length;
      const status = allPaid ? "PAID" : paidCount > 0 ? "PARTIAL" : order.paymentStatus;
      await db
        .update(s.orders)
        .set({ paymentStatus: status, ...(allPaid ? { paidAt: new Date() } : {}) })
        .where(eq(s.orders.id, input.orderId));
      if (order.quote?.request && allPaid) {
        await db.update(s.requests).set({ status: "PAID" }).where(eq(s.requests.id, order.quote.request.id));
        await notify(order.quote.request.buyerId, "PAYMENT_CONFIRMED", "Payment confirmed", `Payment for ${order.orderNumber} confirmed, preparing shipment.`, "/buyer/orders");
      } else if (order.quote?.request && paidCount > 0) {
        await notify(order.quote.request.buyerId, "PAYMENT_CONFIRMED", "Deposit recorded", `Your deposit for ${order.orderNumber} has been recorded. The balance is due on document release.`, "/buyer/orders");
      }
      await logActivity("System", `Payment recorded for ${order.orderNumber} (${status.toLowerCase()}, ${paidCount}/${fresh.length} invoices)`, "order", order.orderNumber);
      return { ok: true, status };
    }),

  /** Buyer confirms delivery → completes the order, releases supplier payment */
  confirmReceipt: authedQuery
    .input(z.object({ orderId: z.number(), note: z.string().optional() }))
    .mutation(async ({ ctx, input }) => {
      const me = await effUser(ctx.user);
      assertBuyer(me);
      const db = getDb();
      const order = await db.query.orders.findFirst({
        where: eq(s.orders.id, input.orderId),
        with: { quote: { with: { request: true } }, shipment: true },
      });
      if (!order || order.quote?.request?.buyerId !== me.id) throw new Error("Order not found");
      await db.update(s.orders).set({ shipmentStatus: "DELIVERED" }).where(eq(s.orders.id, input.orderId));
      if (order.shipment) {
        await db.update(s.shipments).set({ status: "DELIVERED" }).where(eq(s.shipments.id, order.shipment.id));
      }
      if (order.quote?.request) {
        await db.update(s.requests).set({ status: "COMPLETED" }).where(eq(s.requests.id, order.quote.request.id));
      }
      if (order.quote?.supplierId) {
        await notify(order.quote.supplierId, "PAYMENT_RELEASED", "Delivery confirmed, payment released", `Buyer confirmed receipt of ${order.orderNumber}. Payment has been released to your account.`, "/supplier/earnings");
      }
      await logActivity(fmtActor(me), `Confirmed receipt of ${order.orderNumber}, supplier payment released`, "order", order.orderNumber, me.id);
      return { ok: true };
    }),
});
